spring:
  application:
    name: jme-cdct-provider-service
server:
  servlet:
    context-path: /${spring.application.name}
jeap:
  swagger:
    status: OPEN
  security:
    oauth2:
      resourceserver:
        system-name: "jme"
